### ISSUE TITLE
Meta-Issue for the road to release

### ISSUE THREAD

**Issue by Seelengrab** [Seelengrab/Supposition.jl#19]
These must be done before registration:

 - [x] Overall API review
   * #12 and similar considerations
   * #13 
 - [x] Fully customizable configuration
   * #9 
   * #17
 - [x] Organize the repo
   - [x] Create an issue template
   - [x] Create a PR template
   - [x] Find a place for user discussion.
     * ~~No short-form chat, more forum like. Potential: Github Discussion, Discourse?~~
     * This is done now, with Github Discussions: https://github.com/Seelengrab/Supposition.jl/discussions. I'm torn about being centralized on one platform, but it's the easiest thing to do since it doesn't require people to sign up for anything else. If users can report issues/open PRs, they can also participate in the discussion.
